version: 2

jobs:
  build:
    working_directory: ~/core.typed
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn --version
      # remove "Downloaded" and "Downloading" logs
      - run: mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean test
